# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "npm"
    versioning-strategy: "increase"

  - package-ecosystem: "pipx"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "pipx"
    versioning-strategy: "increase"
      
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "pip"        
    versioning-strategy: "increase"
    
   - package-ecosystem: "yarn"
     directory: "/"
     schedule:
       interval: "weekly"
    allow:
       - dependency-type: "all"
    commit-message:
       prefix: "yarn"        
    versioning-strategy: "increase"
